### ISSUE TITLE
No module named 'gym.configuration'

### ISSUE THREAD

**Issue by Kautenja** [ppaquette/gym_pull#10]
I can't import gym_pull because gym has no configuration package.

# versions

- gym-0.10.4
- gym-pull-0.1.7

# steps to reproduce

1. install `gym-pull`
2. import `gym-pull`

# sample

```python
import gym_pull
```

# stack trace

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-1e180c64cd42> in <module>()
----> 1 import gym_pull

/usr/local/lib/python3.6/site-packages/gym_pull/__init__.py in <module>()
      4 
      5 from gym import error
----> 6 from gym.configuration import logger_setup, undo_logger_setup
      7 from gym.utils import reraise
      8 

ModuleNotFoundError: No module named 'gym.configuration'
```

**Comment by jasoriya** [comment]
Just faced the same issue.

**Comment by baggyg** [comment]
I suspect this maybe a Python 3.6 issue. Have you tried within a 3.5 environment?

**Comment by edusco4** [comment]
I am using python 3.5 and yet am faced with the same problem

**Comment by jasoriya** [comment]
This is not a python issue. Gym repo has been changed and is no longer
compatible with gym-pull.

**Comment by ghost** [comment]
any updates ?

**Comment by hqm** [comment]
I am wondering if there is an alternative to gym-pull for installing super mario into openai gym?

**Comment by Kautenja** [comment]
@hqm  I wrote a new gym super mario bros environment [here](https://github.com/Kautenja/gym-super-mario-bros). it's far simpler to use with no need for this extra nonsense. Just install with `pip` and import then you're good to go. The README has the instructions. Enjoy

**Comment by hqm** [comment]
@Kautenja thanks much !!

**Comment by ghost** [comment]
is there a way to install "fceux" it on windows 10 ?

**Comment by Kautenja** [comment]
@NaderNazemi yes FCEUX supports a [Windows version](http://www.fceux.com/web/download.html). To successfully interface Python with FCEUX, you'd need to have selected "Add Python 3.x to PATH" during the Python installation. FCEUX will also need to be installed and added to the Windows PATH. Then you'd just use the Windows command prompt as if it were a standard Unix shell. While theoretically sound, I've not personally tested this. So, your mileage may vary. If you encounter any problems, feel free to open an issue [here](https://github.com/Kautenja/gym-super-mario-bros/issues) and we can get a Windows installation section added to the README with relevant instructions. I've got a windows installation on my gaming rig and can experiment with this some tomorrow :)

**Comment by ghost** [comment]
I would be eternally grateful if there was a step by step guide on how to
implement the steps above.
I am using:
Window 10
Python 3.6
Bless you

**Comment by ghost** [comment]
I installed fceux but now I am having variable path too large issue.
Please note that I am using Anaconda Python.
Thank you

**Comment by JunghoYoo** [comment]
I solved this problem by 'export' as below on command prompt.

Check 'gym_pull' exists on the directory('/usr/local/lib/python3.6/dist-packages') before this command. 


export PYTHONPATH=/usr/local/lib/python3.6/dist-packages

**Comment by Riotpiaole** [comment]
I try to downgrade the gym to 0.9.0 and it works 
try this 
```bash
pip uninstall gym 
pip install gym==0.9.0
```

**Comment by Kautenja** [comment]
Closing this issue as it's just a version control problem. Someone might open a pull request to update the requirements.txt (and setup.py if that's used), but idk if @ppaquette is maintaining this repository anymore.
